In [1]:
import numpy as np

arr1 = np.array([5, 10, 15, 20])
arr1


array([ 5, 10, 15, 20])

In [2]:

scalar = np.array(25)
print(scalar)
print("Dimension:", scalar.ndim)


25
Dimension: 0


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print("Dimension:", arr2.ndim)


[[1 2 3]
 [4 5 6]]
Dimension: 2


In [ ]:
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3)
print("Dimension:", arr3.ndim)


In [4]:

arr_nd2 = np.array([1, 2, 3], ndmin=2)
print(arr_nd2)
print("Dimensions:", arr_nd2.ndim)


[[1 2 3]]
Dimensions: 2


In [5]:
arr_nd4 = np.array([1, 2, 3], ndmin=4)
print(arr_nd4)
print("Dimensions:", arr_nd4.ndim)


[[[[1 2 3]]]]
Dimensions: 4
